### ISSUE TITLE
Suspect use of "Normal" in README (OR fn(a=>1) vs fn((a=>1)) vs fn('a'=>1) vs fn('a'=x>1))

### ISSUE THREAD

**Issue by raiph** [zostay/perl6-KnottyPair#1]
The README suggests "Normal pairs are passed through as named args". But:

```
slurpy-test('a' => 1, 'b' => 2, 'c' => 3);
#> a = [:a(1), :b(2), :c(3)]<>
#> h = {}<>
slurpy-test((a => 1, b => 2, c => 3));
#> a = [:a(1), :b(2), :c(3)]<>
#> h = {}<>
```

**Comment by zostay** [comment]
Right, the ever confusing nuances of Perl 6 pairs. I really wish the implicit *%_ could be dropped from the language and avoid most of the confusion.

**Comment by zostay** [comment]
For the record, bare names imply named-argument conventions, so this is using named args in the first call and the second call, but is a list of Pairs in the third:

``` perl6
sub slurpy-test(*@a, *%h) { dd @a; dd %h }
say "one"; slurpy-test(a => 1, b => 2);
say "two"; slurpy-test(:a(1), :b(2));
say "three"; slurpy-test('a' => 1, 'b' => 2);
```

The output is:

``` perl6
one
[]
{:a(1), :b(2)}
two
[]
{:a(1), :b(2)}
three
[:a(1), :b(2)]
{}
```

So says Larry, so say we all.

However, in the meantime, I've declared KnottyPair to be obsolete with the recent refactoring of Pair, Hashes, Maps, etc.
